[package]
name = "gv100ad"
version = "0.1.0"
authors = ["Janosch Gräf <janosch.graef@gmail.com>"]
edition = "2018"
description = "Parser to read GV100AD files from the Statistisches Bundesamt Germany"

[dependencies]
chrono = "0.4"
thiserror = "1.0"
tracing = "0.1"
